import ReduxProvider from "@/components/ReduxProvider";
import { ThemeProvider } from "@/components/theme-provider";
import "@/styles/globals.css";

//import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" suppressHydrationWarning className="bg-background">
            <body>
                <ReduxProvider>
                    <ThemeProvider
                        attribute="class"
                        enableSystem={false}
                        // defaultTheme="light"
                        forcedTheme="dark"
                    >
                        {children}
                    </ThemeProvider>
                </ReduxProvider>
            </body>
        </html>
    );
}
